declare module 'react-datepicker' {
  import React from 'react';

  export interface ReactDatePickerProps {
    selected?: Date | null;
    onChange?: (date: Date | null) => void;
    dateFormat?: string;
    placeholderText?: string;
    className?: string;
    showTimeSelect?: boolean;
    showTimeSelectOnly?: boolean;
    timeIntervals?: number;
    timeCaption?: string;
    dateFormatCalendar?: string;
    locale?: string;
    minDate?: Date;
    maxDate?: Date;
    filterDate?: (date: Date) => boolean;
    showMonthDropdown?: boolean;
    showYearDropdown?: boolean;
    scrollableYearDropdown?: boolean;
    yearDropdownItemNumber?: number;
    todayButton?: React.ReactNode;
    clearButtonContainerStyle?: React.CSSProperties;
    isClearable?: boolean;
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    autoComplete?: string;
    calendarIconClassName?: string;
    closeOnScroll?: boolean | ((e: UIEvent) => boolean);
    onChangeRaw?: (event: React.ChangeEvent<HTMLInputElement>) => void;
    onFocus?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onSelect?: (date: Date) => void;
    onClickOutside?: () => void;
    onMonthChange?: (date: Date) => void;
    onYearChange?: (date: Date) => void;
    onInputClick?: () => void;
    onInputError?: (err: { code: string; msg: string }) => void;
    preventOpenOnFocus?: boolean;
    onKeyDown?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onClear?: () => void;
    showPopperArrow?: boolean;
    popperProps?: object;
    tabIndex?: number;
    renderCustomHeader?: (props: {
      monthDate: Date;
      date: Date;
      changeYear: (year: number) => void;
      changeMonth: (month: number) => void;
      decreaseMonth: () => void;
      increaseMonth: () => void;
      prevMonthButtonDisabled: boolean;
      nextMonthButtonDisabled: boolean;
    }) => React.ReactNode;
    wrapperClassName?: string;
    calendarClassName?: string;
    dayClassName?: (date: Date) => string | undefined;
    monthClassName?: (date: Date) => string | undefined;
    yearClassName?: (date: Date) => string | undefined;
    peekNextMonth?: boolean;
    showPreviousMonths?: boolean;
    monthsShown?: number;
    keepOpenOnSelect?: boolean;
    closeOnPortalBlur?: boolean;
    enableTabLoop?: boolean;
    inline?: boolean;
    onCalendarOpen?: () => void;
    onCalendarClose?: boolean;
    portalId?: string;
    forceShowMonthNavigation?: boolean;
    showDisabledMonthNavigation?: boolean;
    previousMonthButtonLabel?: React.ReactNode;
    nextMonthButtonLabel?: React.ReactNode;
    previousYearButtonLabel?: React.ReactNode;
    nextYearButtonLabel?: React.ReactNode;
    timeInputLabel?: string;
    shouldCloseOnSelect?: boolean;
    focusTrap?: boolean;
    customTimeInput?: React.ReactNode;
    useShortMonthInDropdown?: boolean;
    shuffleProperties?: boolean;
    excludingNav?: boolean;
    includeDates?: Date[];
    includeTimes?: Date[];
    excludeDates?: Date[];
    excludeTimes?: Date[];
    minTime?: Date;
    maxTime?: Date;
    filterTime?: (time: Date) => boolean;
    showTimeInput?: boolean;
    showMonthYearPicker?: boolean;
    showFullMonthYearPicker?: boolean;
    showTwoColumnMonthYearPicker?: boolean;
    showFourColumnMonthYearPicker?: boolean;
    showYearPicker?: boolean;
    showQuarterYearPicker?: boolean;
    showWeekPicker?: boolean;
    showDayOfMonth?: boolean;
    showWeekNumbers?: boolean;
    outsideClickIgnoreDisabled?: boolean;
    fixedHeight?: boolean;
    timeFormat?: string;
    timeCaption?: string;
    withPortal?: boolean;
    portalId?: string;
    customInput?: React.ReactNode;
    customInputRef?: string;
    dateFormatCalendar?: string;
    calendarStartDay?: number;
    toggleCalendarOnIconClick?: boolean;
    strictParsing?: boolean;
    startDate?: Date | null;
    endDate?: Date | null;
    selectsStart?: boolean;
    selectsEnd?: boolean;
    selectsRange?: boolean;
    selected?: Date | null;
    id?: string;
    name?: string;
    autoComplete?: string;
    disabled?: boolean;
    required?: boolean;
    value?: string;
    defaultValue?: string;
    onChange?: (date: Date | null) => void;
    onFocus?: React.FocusEventHandler<HTMLInputElement>;
    onBlur?: React.FocusEventHandler<HTMLInputElement>;
    onClick?: React.MouseEventHandler<HTMLInputElement>;
    onChangeRaw?: (event: React.ChangeEvent<HTMLInputElement>) => void;
    onKeyDown?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onSelect?: (date: Date) => void;
    onClose?: () => void;
    onCalendarOpen?: () => void;
    onCalendarClose?: () => void;
    minDate?: Date | null;
    maxDate?: Date | null;
    selectsDisabledDaysInRange?: boolean;
    excludeDateIntervals?: Array<{ start: Date; end: Date }>;
    includeDateIntervals?: Array<{ start: Date; end: Date }>;
    highlightDates?: Array<Date | { [key: string]: boolean }>;
    dateFormat?: string | string[];
    timeFormat?: string;
    timeIntervals?: number;
    timeInputLabel?: string;
    showTimeSelect?: boolean;
    showTimeSelectOnly?: boolean;
    timeCaption?: string;
    autoComplete?: string;
  }

  export default class DatePicker extends React.Component<ReactDatePickerProps> {
    get state(): { inputValue: string };
    set state(value: { inputValue: string });
    input: HTMLInputElement | null;
    calendar: HTMLDivElement | null;
    componentDidUpdate(prevProps: ReactDatePickerProps): void;
  }
}